namespace FavoriteShortcut.Services;

/// <summary>
/// 画面に表示する文字列の対訳表（日本語 / 英語）。
///
/// 1 行に「キー・日本語・英語」を並べて持つので、片方だけ訳し忘れることが構造上起きない。
/// 文字列を追加・変更するときはこの表だけを直せばよい。
///
/// キーは "Str." で始める。XAML からは {DynamicResource Str.xxx} で参照するため、
/// テーマの色などと同じ名前空間に並ぶ。接頭辞で衝突を避けている。
/// {0} {1} は <see cref="Loc.T(string, object?[])"/> で埋めるプレースホルダ。
/// </summary>
public static class Strings
{
    public static readonly IReadOnlyDictionary<string, string> Japanese;
    public static readonly IReadOnlyDictionary<string, string> English;

    /// <summary>キーの一覧（検証用）。</summary>
    public static IEnumerable<string> Keys => Japanese.Keys;

    static Strings()
    {
        var ja = new Dictionary<string, string>(StringComparer.Ordinal);
        var en = new Dictionary<string, string>(StringComparer.Ordinal);

        foreach (var (key, jp, eng) in Table)
        {
            // 重複したキーは起動時に気付けるよう例外にする（テストでも検出される）
            ja.Add(key, jp);
            en.Add(key, eng);
        }

        Japanese = ja;
        English = en;
    }

    private static readonly (string Key, string Ja, string En)[] Table =
    {
        // ------------------------------------------------------------ 共通
        ("Str.App.Name", "お気に入りショートカット", "Favorite Shortcuts"),
        ("Str.Common.Cancel", "キャンセル", "Cancel"),
        ("Str.Common.Save", "保存", "Save"),
        ("Str.Common.Delete", "削除", "Delete"),
        ("Str.Common.Close", "閉じる", "Close"),
        ("Str.Common.Rename", "名前変更", "Rename"),
        ("Str.Common.Error", "エラー", "Error"),
        ("Str.Common.ResetDefault", "既定に戻す", "Reset to Default"),
        ("Str.Common.ListSeparator", "、", ", "),
        ("Str.Common.CountItems", "{0} 件", "{0}"),
        ("Str.Common.CannotUndo", "この操作は元に戻せません。", "This cannot be undone."),
        ("Str.Common.ConfirmDeleteTitle", "削除の確認", "Confirm Delete"),
        ("Str.Common.ConfirmDeleteOne", "「{0}」を削除しますか？", "Delete \"{0}\"?"),
        ("Str.Common.SkippedDuplicates", "\n重複のためスキップ: {0} 件", "\nSkipped as duplicates: {0}"),

        // ------------------------------------------------------- 起動・トレイ
        ("Str.App.DbOpenFailed", "データベースを開けませんでした。\n\n保存場所: {0}\n\n{1}",
            "Could not open the database.\n\nLocation: {0}\n\n{1}"),
        ("Str.App.UnexpectedError",
            "予期しないエラーが発生しました。アプリは動作を続けます。\n\n{0}\n\n詳細はログをご確認ください:\n{1}",
            "An unexpected error occurred. The app will keep running.\n\n{0}\n\nSee the log for details:\n{1}"),
        ("Str.Tray.OpenMain", "管理画面を開く(&O)", "&Open Manager"),
        ("Str.Tray.ShowLauncher", "ランチャーを表示(&L)", "Show &Launcher"),
        ("Str.Tray.Settings", "設定(&S)", "&Settings"),
        ("Str.Tray.Exit", "終了(&X)", "E&xit"),
        ("Str.Database.TooNew",
            "データベースのバージョン ({0}) がこのアプリ ({1}) より新しいため開けません。新しいバージョンのアプリをご使用ください。",
            "This database (version {0}) was created by a newer version of the app (this app supports version {1}). Please use a newer version of the app."),

        // --------------------------------------------------------- フォルダ
        ("Str.Folder.All", "すべてのショートカット", "All Shortcuts"),
        ("Str.Folder.Uncategorized", "未分類", "Uncategorized"),
        ("Str.Folder.UncategorizedChoice", "未分類（フォルダに入れない）", "Uncategorized (no folder)"),
        ("Str.Folder.Section", "フォルダ", "Folders"),
        ("Str.Folder.NameLabel", "フォルダ名", "Folder name"),
        ("Str.Folder.NewTitle", "新しいフォルダ", "New Folder"),
        ("Str.Folder.NewSub", "新しいサブフォルダ", "New Subfolder"),
        ("Str.Folder.NewTooltip", "新しいフォルダを作成", "Create a new folder"),
        ("Str.Folder.RenameTitle", "フォルダ名の変更", "Rename Folder"),
        ("Str.Folder.CannotMoveIntoSelf", "フォルダを自分自身やその配下へは移動できません。",
            "A folder cannot be moved into itself or into one of its subfolders."),
        ("Str.Folder.SeedWork", "仕事", "Work"),
        ("Str.Folder.SeedDevelopment", "開発", "Development"),
        ("Str.Folder.SeedPersonal", "個人", "Personal"),
        ("Str.Folder.SeedOther", "その他", "Other"),

        // ----------------------------------------------------------- 種類
        ("Str.Type.Web", "Web サイト", "Website"),
        ("Str.Type.Folder", "フォルダ", "Folder"),
        ("Str.Type.File", "ファイル", "File"),
        ("Str.Type.Application", "アプリケーション", "Application"),
        ("Str.Type.Unknown", "不明", "Unknown"),

        // ------------------------------------------------------- ホットキー
        ("Str.HotKey.NotSet", "（未設定）", "(Not set)"),

        // ----------------------------------------------------------- 起動
        ("Str.Launch.CannotOpen", "開けませんでした", "Could not open"),
        ("Str.Launch.NoTarget", "URL / パスが設定されていません。", "No URL or path is set."),
        ("Str.Launch.FolderNotFound", "フォルダが見つかりません。", "Folder not found."),
        ("Str.Launch.FileNotFound", "ファイルが見つかりません。", "File not found."),
        ("Str.Launch.NotSupported", "この項目には対応していません", "Not available for this item"),
        ("Str.Launch.WebHasNoFolder", "Web サイトにはフォルダがありません。", "Websites do not have a folder location."),
        ("Str.Launch.LocationNotFound", "場所が見つかりません。", "Location not found."),
        ("Str.Launch.KeptEditHint", "登録内容は残っています。編集画面からパスを修正できます。",
            "The shortcut has been kept. You can fix the path from the edit screen."),
        ("Str.Launch.Kept", "登録内容はそのまま残っています。", "The shortcut has been kept as is."),

        // ------------------------------------------------------ 管理画面
        ("Str.Main.SearchPlaceholder", "検索...  （タイトル / タグ / フォルダ / URL・パス）",
            "Search...  (title / tag / folder / URL or path)"),
        ("Str.Main.ClearSearchTooltip", "検索条件をクリア (Esc)", "Clear search (Esc)"),
        ("Str.Main.CardView", "▦ カード", "▦ Cards"),
        ("Str.Main.ListView", "☰ リスト", "☰ List"),
        ("Str.Main.CardViewTooltip", "カード表示", "Card view"),
        ("Str.Main.ListViewTooltip", "リスト表示", "List view"),
        ("Str.Main.New", "＋ 新規登録", "＋ New"),
        ("Str.Main.NewTooltip", "新しいショートカットを登録 (Ctrl+N)", "Add a new shortcut (Ctrl+N)"),
        ("Str.Main.MoreTooltip", "その他の操作", "More actions"),
        ("Str.Main.EmptyTitle", "ショートカットがありません", "No shortcuts yet"),
        ("Str.Main.EmptyHint",
            "「＋ 新規登録」から追加するか、エクスプローラーからファイル・フォルダをここへドラッグしてください。",
            "Click \"＋ New\", or drag files and folders here from File Explorer."),
        ("Str.Main.NotFoundTitle", "見つかりませんでした", "No matches"),
        ("Str.Main.NotFoundHint",
            "別のキーワードをお試しください。タイトル・タグ・フォルダ名・URL / パスが検索対象です。",
            "Try a different keyword. Titles, tags, folder names and URLs / paths are searched."),
        ("Str.Main.HotKeyNotRegistered", "ランチャーのホットキーは未登録です（設定で変更できます）",
            "Launcher hotkey is not registered (you can change it in Settings)"),
        ("Str.Main.HotKeyHint", "ランチャー: {0}", "Launcher: {0}"),
        ("Str.Main.CountSearching", "{0} 件ヒット / このフォルダ {1} 件", "{0} matches / {1} in this folder"),
        ("Str.Main.Count", "{0} 件", "{0} items"),
        ("Str.Main.Truncated",
            "表示が重くならないよう、カード表示では先頭 {0} 件のみ表示しています。検索で絞り込むか、リスト表示に切り替えるとすべて表示できます。",
            "To keep things responsive, card view shows only the first {0} items. Narrow the list with search, or switch to list view to see everything."),
        ("Str.Main.Status", "全 {0} 件 / フォルダ {1} 件 / タグ {2} 件", "{0} shortcuts / {1} folders / {2} tags"),
        ("Str.Main.CopySuffix", "{0} のコピー", "{0} (copy)"),
        ("Str.Main.Copied", "クリップボードにコピーしました。", "Copied to the clipboard."),
        ("Str.Main.DeleteMany", "選択した {0} 件のショートカットを削除しますか？", "Delete the {0} selected shortcuts?"),
        ("Str.Main.AddManyTitle", "まとめて登録", "Add Multiple"),
        ("Str.Main.AddMany", "{0} 件のファイル / フォルダをショートカットとして登録しますか？",
            "Add {0} files / folders as shortcuts?"),

        // ---------------------------------------------------- メニュー
        ("Str.Menu.Settings", "設定...", "Settings..."),
        ("Str.Menu.ImportBookmarks", "ブラウザのお気に入りを取り込む...", "Import Browser Bookmarks..."),
        ("Str.Menu.Export", "エクスポート（ZIP に保存）...", "Export (Save as ZIP)..."),
        ("Str.Menu.Import", "インポート（ZIP から取り込み）...", "Import (Load from ZIP)..."),
        ("Str.Menu.BackupNow", "今すぐバックアップを作成", "Back Up Now"),
        ("Str.Menu.OpenDataFolder", "データ保存場所を開く", "Open Data Folder"),
        ("Str.Menu.ShowLauncher", "ランチャーを表示", "Show Launcher"),
        ("Str.Menu.Help", "使い方（README）", "How to Use"),
        ("Str.Menu.Open", "開く", "Open"),
        ("Str.Menu.Edit", "編集...", "Edit..."),
        ("Str.Menu.Duplicate", "複製", "Duplicate"),
        ("Str.Menu.CopyTarget", "URL / パスをコピー", "Copy URL / Path"),
        ("Str.Menu.CopyTitle", "タイトルをコピー", "Copy Title"),
        ("Str.Menu.Reveal", "保存先フォルダを開く", "Open Containing Folder"),
        ("Str.Menu.RefreshIcon", "アイコンを再取得", "Refresh Icon"),
        ("Str.Menu.MoveTo", "移動先フォルダ...", "Move to Folder..."),

        // ----------------------------------------------------------- タグ
        ("Str.Tag.Section", "タグ", "Tags"),
        ("Str.Tag.Manage", "管理", "Manage"),
        ("Str.Tag.ManageTooltip", "タグの名前変更・削除", "Rename or delete tags"),
        ("Str.Tag.None", "タグはまだありません", "No tags yet"),
        ("Str.Tag.SearchTooltip", "「{0}」で検索", "Search for \"{0}\""),
        ("Str.Tag.InputPlaceholder", "タグを入力して Space で確定（例: AI 開発 仕事）",
            "Type a tag and press Space (e.g. AI dev work)"),
        ("Str.Tag.RemoveTooltip", "「{0}」を削除", "Remove \"{0}\""),
        ("Str.TagManager.Title", "タグの管理", "Manage Tags"),
        ("Str.TagManager.Heading", "登録されているタグ", "Tags"),
        ("Str.TagManager.Filter", "タグを絞り込む...", "Filter tags..."),
        ("Str.TagManager.RenameTitle", "タグ名の変更", "Rename Tag"),
        ("Str.TagManager.RenamePrompt", "「{0}」の新しい名前", "New name for \"{0}\""),
        ("Str.TagManager.DeleteTitle", "タグの削除", "Delete Tag"),
        ("Str.TagManager.DeleteConfirm",
            "タグ「{0}」を削除しますか？\n\n{1} 件のショートカットからこのタグが外れます。ショートカット自体は削除されません。",
            "Delete the tag \"{0}\"?\n\nIt will be removed from {1} shortcuts. The shortcuts themselves will not be deleted."),

        // --------------------------------------------- エクスポート / インポート
        ("Str.Transfer.Filter", "お気に入りショートカット データ (*.zip)|*.zip", "Favorite Shortcuts data (*.zip)|*.zip"),
        ("Str.Transfer.NoDatabase", "このファイルにはデータベースが含まれていません。", "This file does not contain a database."),
        ("Str.Export.DialogTitle", "エクスポート先を選択", "Choose Export Location"),
        ("Str.Export.DoneTitle", "エクスポート完了", "Export Complete"),
        ("Str.Export.Done",
            "エクスポートしました。\n\n{0}\n\nこのファイルを別のPCでインポートすると、フォルダ・タグ・アイコンごと復元できます。",
            "Export complete.\n\n{0}\n\nImport this file on another PC to restore everything, including folders, tags and icons."),
        ("Str.Export.Failed", "エクスポートに失敗しました。\n\n{0}", "Export failed.\n\n{0}"),
        ("Str.Import.DialogTitle", "インポートするファイルを選択", "Choose a File to Import"),
        ("Str.Import.CannotImportTitle", "インポートできません", "Cannot Import"),
        ("Str.Import.NotOurFile", "このファイルは、このアプリのエクスポートデータではないようです。",
            "This file does not appear to be export data from this app."),
        ("Str.Import.DoneTitle", "インポート完了", "Import Complete"),
        ("Str.Import.Done",
            "インポートが完了しました。\n\nフォルダ: {0} 件\nショートカット: {1} 件{2}\n\n念のため、取り込み前のデータを次の場所にバックアップしました:\n{3}",
            "Import complete.\n\nFolders: {0}\nShortcuts: {1}{2}\n\nYour previous data was backed up to:\n{3}"),
        ("Str.Import.Failed",
            "インポートに失敗しました。現在のデータは変更されていないか、バックアップから復元できます。\n\n{0}",
            "Import failed. Your current data was either left unchanged or can be restored from the backup.\n\n{0}"),
        ("Str.ImportMode.Title", "インポート", "Import"),
        ("Str.ImportMode.Heading", "このデータを取り込みます", "Import this data"),
        ("Str.ImportMode.Method", "取り込み方法", "Import method"),
        ("Str.ImportMode.Merge", "現在のデータを残して追加する", "Add to my current data"),
        ("Str.ImportMode.MergeNote",
            "同じ構成のフォルダはまとめられ、まったく同じ内容のショートカットは追加されません。",
            "Folders with the same structure are merged, and identical shortcuts are not added again."),
        ("Str.ImportMode.Replace", "現在のデータをすべて置き換える", "Replace all my current data"),
        ("Str.ImportMode.ReplaceNote",
            "今このPCにあるフォルダ・ショートカット・タグ・設定は削除され、取り込んだ内容に入れ替わります。",
            "The folders, shortcuts, tags and settings on this PC will be deleted and replaced with the imported data."),
        ("Str.ImportMode.BackupNote",
            "取り込みの直前に、現在のデータのバックアップを自動で作成します。うまくいかなかった場合はそこから戻せます。",
            "A backup of your current data is created automatically right before the import, so you can restore it if something goes wrong."),
        ("Str.ImportMode.Summary", "フォルダ {0} 件 / ショートカット {1} 件 / タグ {2} 件",
            "{0} folders / {1} shortcuts / {2} tags"),
        ("Str.ImportMode.ExportedAt", "エクスポート日時: {0}　/　作成バージョン: {1}",
            "Exported: {0}  /  App version: {1}"),
        ("Str.ImportMode.ReplaceConfirmTitle", "置き換えの確認", "Confirm Replace"),
        ("Str.ImportMode.ReplaceConfirm",
            "現在のフォルダ・ショートカット・タグ・設定をすべて削除して、取り込んだ内容に置き換えます。\n\nよろしいですか？",
            "All current folders, shortcuts, tags and settings will be deleted and replaced with the imported data.\n\nContinue?"),
        ("Str.Backup.Title", "バックアップ", "Backup"),
        ("Str.Backup.Done", "バックアップを作成しました。\n\n{0}", "Backup created.\n\n{0}"),
        ("Str.Backup.Failed", "バックアップに失敗しました。\n\n{0}", "Backup failed.\n\n{0}"),

        // ----------------------------------------------------------- 使い方
        ("Str.Help.Title", "使い方", "How to Use"),
        ("Str.Help.Body",
            "基本的な使い方\n\n" +
            "・「＋ 新規登録」または エクスプローラーからのドラッグ＆ドロップで登録します。\n" +
            "・タグは入力して Space キーで確定します（日本語IMEの変換用スペースとは競合しません）。\n" +
            "・上部の検索欄では、タイトル・タグ・フォルダ名・URL / パスをまとめて検索できます。\n" +
            "・どのアプリを使っていても、ホットキー（既定 Ctrl+Space）でランチャーを呼び出せます。\n" +
            "・ランチャーでは ↑↓ で選択、Enter で起動、Esc で閉じます。",
            "Getting started\n\n" +
            "• Add shortcuts with \"＋ New\", or by dragging files and folders in from File Explorer.\n" +
            "• Type a tag and press Space to add it.\n" +
            "• The search box at the top searches titles, tags, folder names and URLs / paths at once.\n" +
            "• Open the launcher from any app with the hotkey (Ctrl+Space by default).\n" +
            "• In the launcher, use ↑↓ to select, Enter to open, and Esc to close."),

        // ------------------------------------------------------ 登録・編集
        ("Str.Edit.TitleNew", "ショートカットの登録", "Add Shortcut"),
        ("Str.Edit.TitleEdit", "ショートカットの編集", "Edit Shortcut"),
        ("Str.Edit.Add", "登録", "Add"),
        ("Str.Edit.Target", "URL / パス", "URL / Path"),
        ("Str.Edit.BrowseFile", "ファイル...", "File..."),
        ("Str.Edit.BrowseFolder", "フォルダ...", "Folder..."),
        ("Str.Edit.TitleLabel", "タイトル", "Title"),
        ("Str.Edit.TagHint", "入力して Space キーで確定 / Backspace で直前を削除",
            "Press Space to add a tag / Backspace removes the last one"),
        ("Str.Edit.Folder", "フォルダ", "Folder"),
        ("Str.Edit.NewFolder", "新規フォルダ...", "New Folder..."),
        ("Str.Edit.Icon", "アイコン", "Icon"),
        ("Str.Edit.ChooseImage", "画像を選択...", "Choose Image..."),
        ("Str.Edit.FetchFavicon", "favicon を取得", "Get Favicon"),
        ("Str.Edit.Fetching", "取得中...", "Fetching..."),
        ("Str.Edit.Note", "メモ（任意・検索対象になります）", "Notes (optional, searchable)"),
        ("Str.Edit.TargetHint", "Web の URL、フォルダのパス、ファイルのパスを入力できます。",
            "Enter a web URL, a folder path, or a file path."),
        ("Str.Edit.TypeInfo", "種類: {0}", "Type: {0}"),
        ("Str.Edit.SavedAs", "　→ 保存時: {0}", "   → Saved as: {0}"),
        ("Str.Edit.PathMissing", "　⚠ 現在このパスは見つかりません（そのまま登録できます）",
            "   ⚠ This path cannot be found right now (you can still save it)"),
        ("Str.Edit.IconAutoWeb", "Web サイトの favicon を自動取得します（取得できない場合は既定アイコン）。",
            "The website's favicon is fetched automatically (a default icon is used if it cannot be found)."),
        ("Str.Edit.IconAutoFolder", "Windows のフォルダアイコンを表示します。", "The Windows folder icon is shown."),
        ("Str.Edit.IconAutoFile", "ファイルに関連付けられたアイコンを表示します。",
            "The icon of the associated app is shown."),
        ("Str.Edit.IconAutoDefault", "既定のアイコンを表示します。", "A default icon is shown."),
        ("Str.Edit.IconCustom", "指定した画像を使用します。", "Your chosen image is used."),
        ("Str.Edit.IconCached", "取得済みの favicon を使用します。", "The saved favicon is used."),
        ("Str.Edit.ChooseImageTitle", "アイコンに使う画像を選択", "Choose an Image for the Icon"),
        ("Str.Edit.ImageFilter",
            "画像ファイル (*.png;*.ico;*.jpg;*.jpeg;*.gif;*.bmp)|*.png;*.ico;*.jpg;*.jpeg;*.gif;*.bmp",
            "Image files (*.png;*.ico;*.jpg;*.jpeg;*.gif;*.bmp)|*.png;*.ico;*.jpg;*.jpeg;*.gif;*.bmp"),
        ("Str.Edit.ImageUnreadable", "この画像は読み込めませんでした。別のファイルをお試しください。",
            "This image could not be loaded. Please try another file."),
        ("Str.Edit.NoHost", "URL からサイト名を読み取れませんでした。", "Could not read a site name from the URL."),
        ("Str.Edit.FaviconFailed",
            "favicon を取得できませんでした。\n\nサイトが favicon を公開していないか、ネットワークに接続できていない可能性があります。「画像を選択...」から任意の画像を設定することもできます。",
            "Could not get the favicon.\n\nThe site may not publish one, or you may be offline. You can also set any image with \"Choose Image...\"."),
        ("Str.Edit.ChooseFileTitle", "ファイルを選択", "Choose a File"),
        ("Str.Edit.AllFilesFilter", "すべてのファイル (*.*)|*.*", "All files (*.*)|*.*"),
        ("Str.Edit.ChooseFolderTitle", "フォルダを選択", "Choose a Folder"),
        ("Str.Edit.TargetRequired", "URL / パスを入力してください。", "Please enter a URL or path."),
        ("Str.Edit.TitleRequired", "タイトルを入力してください。", "Please enter a title."),
        ("Str.Edit.SaveFailed", "保存できませんでした: {0}", "Could not save: {0}"),
        ("Str.Edit.DuplicateTitle", "重複の確認", "Possible Duplicate"),
        ("Str.Edit.Duplicate",
            "同じ URL / パスが「{0}」（{1}）に登録されています。\n\nこのまま登録しますか？",
            "The same URL / path is already registered as \"{0}\" ({1}).\n\nSave anyway?"),

        // --------------------------------------------------------- ランチャー
        ("Str.Launcher.Title", "ランチャー", "Launcher"),
        ("Str.Launcher.Placeholder", "検索してEnterで起動", "Type to search, Enter to open"),
        ("Str.Launcher.Footer", "↑↓ 選択　Enter 起動　Esc 閉じる", "↑↓ Select    Enter Open    Esc Close"),
        ("Str.Launcher.Results", "検索結果（{0} 件）", "Results ({0})"),
        ("Str.Launcher.Recent", "最近使った項目", "Recently Used"),
        ("Str.Launcher.NoMatch",
            "該当するショートカットがありません。タイトル・タグ・フォルダ名・URL / パスが検索対象です。",
            "No matching shortcuts. Titles, tags, folder names and URLs / paths are searched."),
        ("Str.Launcher.NoShortcuts", "まだショートカットが登録されていません。管理画面から登録してください。",
            "No shortcuts yet. Add some from the manager window."),
        ("Str.Launcher.TypeKeyword", "キーワードを入力してください。", "Type a keyword."),
        ("Str.Launcher.Total", "全 {0} 件", "{0} total"),

        // --------------------------------------------------------------- 設定
        ("Str.Settings.Title", "設定", "Settings"),
        ("Str.Settings.Display", "表示", "Display"),
        ("Str.Settings.Language", "言語", "Language"),
        ("Str.Settings.LanguageAuto", "自動（Windows の設定に従う）", "Automatic (follow Windows)"),
        ("Str.Settings.LanguageNameJapanese", "日本語", "Japanese"),
        ("Str.Settings.LanguageNameEnglish", "英語", "English"),
        ("Str.Settings.LanguageAutoNote", "「自動」の場合: Windows の表示言語 {0} → {1}で表示します",
            "With Automatic: Windows display language is {0} → shown in {1}"),
        ("Str.Settings.Theme", "テーマ", "Theme"),
        ("Str.Settings.ThemeLight", "ライト", "Light"),
        ("Str.Settings.ThemeDark", "ダーク", "Dark"),
        ("Str.Settings.ViewMode", "一覧の表示形式", "List style"),
        ("Str.Settings.IconSize", "アイコンサイズ", "Icon size"),
        ("Str.Settings.IconSmall", "小 (24px)", "Small (24px)"),
        ("Str.Settings.IconNormal", "標準 (32px)", "Normal (32px)"),
        ("Str.Settings.IconLarge", "大 (48px)", "Large (48px)"),
        ("Str.Settings.IconXLarge", "特大 (64px)", "Extra large (64px)"),
        ("Str.Settings.Launcher", "ランチャー", "Launcher"),
        ("Str.Settings.HotKey", "呼び出しキー", "Hotkey"),
        ("Str.Settings.Change", "変更", "Change"),
        ("Str.Settings.ShowRecent", "検索欄が空のときに「最近使った項目」を表示する",
            "Show \"Recently Used\" when the search box is empty"),
        ("Str.Settings.MaxResults", "最大表示件数", "Max results"),
        ("Str.Settings.Startup", "起動と常駐", "Startup & Background"),
        ("Str.Settings.MinimizeToTray", "ウィンドウを閉じても終了せず、タスクトレイに常駐する",
            "Keep running in the notification area when the window is closed"),
        ("Str.Settings.MinimizeToTrayNote",
            "常駐しているあいだは、他のアプリを使っていてもホットキーでランチャーを呼び出せます。完全に終了するにはトレイアイコンの「終了」を使います。",
            "While running in the background, you can open the launcher with the hotkey from any app. To quit completely, use \"Exit\" on the tray icon."),
        ("Str.Settings.StartMinimized", "起動時はウィンドウを表示せず、トレイ常駐で始める",
            "Start in the notification area without showing the window"),
        ("Str.Settings.RunAtStartup", "Windows へのサインイン時に自動起動する",
            "Start automatically when I sign in to Windows"),
        ("Str.Settings.RunAtStartupNote",
            "EXE を別の場所へ移動した場合は、自動起動をいったんオフにしてから入れ直してください。",
            "If you move the EXE, turn this off and then on again."),
        ("Str.Settings.RestoreFolder", "次回起動時に、最後に開いていたフォルダを選択する",
            "Reopen the last selected folder at startup"),
        ("Str.Settings.Icons", "アイコン", "Icons"),
        ("Str.Settings.BrowserIconCache", "ブラウザが保存しているアイコンを利用する",
            "Use icons saved by your web browsers"),
        ("Str.Settings.BrowserIconCacheNote",
            "Chrome / Edge / Brave / Firefox などが保存済みのアイコンを読み取ります。通信は行わず、登録済みの URL だけを検索します。認証が必要な社内サイトや、直接取得できないサイトのアイコンも表示できます。",
            "Reads icons already saved by Chrome, Edge, Brave, Firefox and others. Nothing is sent over the network, and only your registered URLs are looked up. This also shows icons for intranet sites that require sign-in and for sites that cannot be fetched directly."),
        ("Str.Settings.BrowsersFound", "見つかったブラウザ: {0}", "Browsers found: {0}"),
        ("Str.Settings.NoBrowsers", "このPCでは対象のブラウザが見つかりませんでした。",
            "No supported browsers were found on this PC."),
        ("Str.Settings.CleanIcons", "未使用のアイコンを整理", "Clean Up Unused Icons"),
        ("Str.Settings.CleanNone", "整理の必要はありませんでした。", "Nothing to clean up."),
        ("Str.Settings.CleanDone", "{0} 個のアイコンファイルを削除しました。", "Deleted {0} icon files."),
        ("Str.Settings.Data", "データ", "Data"),
        ("Str.Settings.DataLocation", "保存場所", "Location"),
        ("Str.Settings.OpenFolder", "フォルダを開く", "Open Folder"),
        ("Str.Settings.ChangeLocation", "保存場所を変更...", "Change Location..."),
        ("Str.Settings.OpenBackup", "バックアップフォルダを開く", "Open Backup Folder"),
        ("Str.Settings.OpenLog", "ログを開く", "Open Log"),
        ("Str.Settings.About", "このアプリについて", "About"),
        ("Str.Settings.Version", "{0}  バージョン {1}", "{0}  version {1}"),
        ("Str.Settings.Stats", "ショートカット {0} 件 / フォルダ {1} 件 / タグ {2} 件",
            "{0} shortcuts / {1} folders / {2} tags"),
        ("Str.Settings.DataNoteFallback",
            "EXE のある場所には書き込めないため、上記の場所を使用しています。EXE と同じ場所の Data フォルダにまとめたい場合は、EXE を書き込み可能な場所（デスクトップやドキュメント、USB メモリなど）へ移してください。",
            "The EXE's folder is not writable, so the location above is used instead. To keep your data in a Data folder next to the EXE, move the EXE somewhere writable (such as the Desktop, Documents, or a USB drive)."),
        ("Str.Settings.DataNoteDefault",
            "既定では EXE と同じ場所の Data フォルダに保存します。EXE とこのフォルダを一緒にコピーすれば、別のPCでもそのまま同じ内容で使えます。保存場所を変更した場合は次回起動時から有効になります（現在のデータは自動では移動しません）。",
            "By default, data is saved in a Data folder next to the EXE. Copy the EXE together with that folder to use the same data on another PC. A changed location takes effect the next time the app starts (existing data is not moved automatically)."),
        ("Str.Settings.PressKeys", "キーを押してください...", "Press keys..."),
        ("Str.Settings.CaptureHint", "Ctrl / Shift / Alt / Win と組み合わせたキーを押してください（Esc で中止）。",
            "Press a key together with Ctrl / Shift / Alt / Win (Esc to cancel)."),
        ("Str.Settings.NeedModifier", "修飾キー（Ctrl / Shift / Alt / Win）と組み合わせて押してください。",
            "Please include a modifier key (Ctrl / Shift / Alt / Win)."),
        ("Str.Settings.HotKeyInUse",
            "このキーは他のアプリまたは Windows が使用しているため登録できませんでした。別のキーに変更してください。",
            "This key could not be registered because another app or Windows is using it. Please choose a different key."),
        ("Str.Settings.HotKeyConflictHint", "他のアプリと競合する場合は、別の組み合わせに変更してください。",
            "If it conflicts with another app, choose a different combination."),
        ("Str.Settings.HotKeyTitle", "ホットキー", "Hotkey"),
        ("Str.Settings.HotKeyFailed",
            "ホットキー {0} を登録できませんでした。\n\n他のアプリまたは Windows が同じキーを使用している可能性があります。設定画面から別の組み合わせに変更してください。",
            "The hotkey {0} could not be registered.\n\nAnother app or Windows may be using the same key. Please choose a different combination in Settings."),
        ("Str.Settings.StartupTitle", "自動起動", "Startup"),
        ("Str.Settings.StartupFailed", "自動起動の設定を変更できませんでした。", "Could not change the startup setting."),
        ("Str.Settings.LogTitle", "ログ", "Log"),
        ("Str.Settings.NoLog", "ログファイルはまだありません。", "There is no log file yet."),
        ("Str.Settings.ChooseDataFolder", "データの保存場所を選択", "Choose Data Location"),
        ("Str.Settings.NextLaunch", "{0}\n→ 次回起動から: {1}", "{0}\n→ From next launch: {1}"),
        ("Str.Settings.NextLaunchDefault", "{0}\n→ 次回起動から: {1}（既定）", "{0}\n→ From next launch: {1} (default)"),
        ("Str.Settings.LocationTitle", "保存場所", "Data Location"),
        ("Str.Settings.LocationChanged",
            "データの保存場所を変更しました。次回このアプリを起動したときから有効になります。\n\n現在のデータは自動では移動しません。必要であれば、いったんエクスポートしてから新しい場所でインポートしてください。",
            "The data location has been changed. It takes effect the next time the app starts.\n\nExisting data is not moved automatically. If needed, export it first and then import it in the new location."),
        ("Str.Settings.LocationFailed", "保存場所を変更できませんでした。\n\n{0}", "Could not change the data location.\n\n{0}"),

        // ------------------------------------------------------ 小さなダイアログ
        ("Str.TextInput.Title", "入力", "Input"),
        ("Str.TextInput.Required", "1 文字以上入力してください。", "Please enter at least one character."),
        ("Str.FolderPicker.Title", "移動先フォルダの選択", "Choose Destination Folder"),
        ("Str.FolderPicker.Prompt", "移動先のフォルダを選んでください", "Choose a destination folder"),
        ("Str.FolderPicker.Move", "移動", "Move"),
        ("Str.FolderDelete.Title", "フォルダの削除", "Delete Folder"),
        ("Str.FolderDelete.ContentsLabel", "中のショートカットの扱い", "What to do with the shortcuts inside"),
        ("Str.FolderDelete.Keep", "未分類へ移動する（削除しない）", "Move them to Uncategorized (keep them)"),
        ("Str.FolderDelete.DeleteToo", "ショートカットも一緒に削除する", "Delete them as well"),
        ("Str.FolderDelete.Confirm", "削除する", "Delete"),
        ("Str.FolderDelete.SubFolders", "サブフォルダ {0} 個", "{0} subfolders"),
        ("Str.FolderDelete.Shortcuts", "ショートカット {0} 件", "{0} shortcuts"),
        ("Str.FolderDelete.Empty", "このフォルダは空です。この操作は元に戻せません。",
            "This folder is empty. This cannot be undone."),
        ("Str.FolderDelete.Contains",
            "このフォルダには {0} が含まれています。サブフォルダは一緒に削除されます。この操作は元に戻せません。",
            "This folder contains {0}. Subfolders will be deleted as well. This cannot be undone."),

        // ------------------------------------------------ お気に入りの取り込み
        ("Str.Bookmark.Title", "ブラウザのお気に入りを取り込む", "Import Browser Bookmarks"),
        ("Str.Bookmark.Source", "取り込み元のブラウザ", "Import from"),
        ("Str.Bookmark.Range", "取り込む範囲", "What to import"),
        ("Str.Bookmark.Destination", "取り込み先", "Import into"),
        ("Str.Bookmark.NewFolder", "新しいフォルダを作る", "Create a new folder"),
        ("Str.Bookmark.ExistingFolder", "既存のフォルダへ", "Existing folder"),
        ("Str.Bookmark.KeepStructure", "ブラウザのフォルダ構成を再現する", "Keep the browser's folder structure"),
        ("Str.Bookmark.SkipDuplicates", "すでに登録済みの URL は取り込まない", "Skip URLs that are already registered"),
        ("Str.Bookmark.AddTag", "取り込んだ項目にタグを付ける", "Add a tag to imported items"),
        ("Str.Bookmark.Import", "取り込む", "Import"),
        ("Str.Bookmark.NoBrowsers",
            "お気に入りを読み取れるブラウザが見つかりませんでした。Microsoft Edge または Google Chrome がインストールされ、一度でも起動されている必要があります。",
            "No browser with readable bookmarks was found. Microsoft Edge or Google Chrome must be installed and started at least once."),
        ("Str.Bookmark.ReadFailed", "このブラウザのお気に入りを読めませんでした。\n{0}",
            "Could not read this browser's bookmarks.\n{0}"),
        ("Str.Bookmark.DefaultFolderName", "{0} のお気に入り", "{0} Bookmarks"),
        ("Str.Bookmark.NoBookmarks", "お気に入りが登録されていません。", "No bookmarks found."),
        ("Str.Bookmark.Untitled", "（名前なし）", "(Untitled)"),
        ("Str.Bookmark.RootCount", "　{0} 件", "   {0}"),
        ("Str.Bookmark.Summary", "ショートカット {0} 件 / フォルダ {1} 個", "{0} shortcuts / {1} folders"),
        ("Str.Bookmark.SummaryNoFolders", "ショートカット {0} 件", "{0} shortcuts"),
        ("Str.Bookmark.ImportFailed",
            "取り込み中にエラーが発生しました。\n\nそこまでに取り込んだ内容は保存されています。\n\n{0}",
            "An error occurred during the import.\n\nEverything imported up to that point has been saved.\n\n{0}"),
        ("Str.Bookmark.FolderNameRequired", "作成するフォルダ名を入力してください。",
            "Please enter a name for the new folder."),
        ("Str.Bookmark.ProfileFormat", "{0}（{1}）", "{0} ({1})"),
        ("Str.Bookmark.DoneTitle", "取り込み完了", "Import Complete"),
        ("Str.Bookmark.Done",
            "お気に入りを取り込みました。\n\n取り込んだショートカット: {0} 件{1}\n\nアイコンは順次取得されます。",
            "Bookmarks imported.\n\nShortcuts added: {0}{1}\n\nIcons will appear shortly."),
    };
}
